core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
	path('',views.index, name = "index"),
	path('add_stock/',views.ingresar_stock, name = "add_stock"),
	path('add_material/',views.crearMaterial, name = "add_material"),
	path('admin_usuario/',views.admin_usuario, name = "admin_usuario"),
	path('admin_pastel/',views.admin_pastel, name = "admin_pastel"),
	path('pedidos/',views.pedidos, name = "pedidos"),
	path('create_base/',views.create_base, name = "create_base"),
	path('create_pastel/',views.create_pastel, name = "create_pastel"),
]

pasteles/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('pasteles_auth.urls'), name='auth'),
    path('', include('core.urls'), name='core'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.utils import timezone
from datetime import date
from django.db import models
from core.defines import *
from django.contrib.auth.models import User
from django.db.models.signals import m2m_changed
from django.core.exceptions import ValidationError

class Stock(models.Model):
	medida = models.CharField(
				max_length=2,
				choices= MEDIDA_CHOICE,
				default= MEDIDA_DEFAULT
			)
	cantidad = models.IntegerField(default=0)
	def __str__(self):
		return str(self.cantidad) + " " + self.medida 

class Material(models.Model):
	tipo = models.CharField(max_length=2,choices=MATERIA_TIPO_CHOICES,default=MATERIA_TIPO_DEFAULT)
	nombre = models.CharField(max_length=240)
	stock = models.OneToOneField(Stock,on_delete=models.CASCADE, blank = True)
	def __str__(self):
		return self.nombre
		
	def total(self):
		return '{} {}' . format(self.stock.cantidad, self.stock.medida)

class Cliente(models.Model):
	userprofile = models.ForeignKey('PerfilUsuario',null=True,default=None,on_delete=models.SET_NULL)
	nombre = models.CharField(max_length=240)
	apellido = models.CharField(max_length=240)
	mail = models.CharField(max_length=240)
	def __str__(self):
		return self.nombre
	
class Pastel(models.Model):
	nombre = models.CharField(max_length=240)
	cover = models.CharField(
		max_length=2,
		choices=COVER_CHOICE,
		default=COVER_DEFAULT
	)
	personas = models.IntegerField(default=20)

	capas = models.ManyToManyField("CapaPastel",related_name="capas_pastel",blank=True)
	base = models.ForeignKey("BasePastel",null=True,default=None,on_delete=models.CASCADE)
	vegano = models.BooleanField(default=False)
	image = models.ImageField(upload_to='pasteles',default=None)
	celiaco = models.BooleanField(default=False)
	def get_capas(self):
		salida = ""
		i = 1
		for capa in self.capas.all():
			if i == 1:
				salida += "%d. %s con %s" % (i,capa.crema,capa.get_ingredientes())
			else:
				salida += "<br>%d. %s con %s" % (i,capa.crema,capa.get_ingredientes())
			i+=1
		return salida

	def __str__(self):
		return self.nombre


class CantReceta(models.Model):
	ingrediente = models.ForeignKey(Material,null=True,on_delete=models.SET_NULL)
	cantidad = models.IntegerField(default=0)
	def cantidad_total(self):
		return '{} {}'.format(self.cantidad, self.ingrediente.stock.medida)

class BasePastel(models.Model):
	nombre = models.CharField(max_length=500,null=True,blank=True)
	receta = models.ManyToManyField(CantReceta,blank=True)
	
	def get_receta(self):
		salida = ""
		for cant in self.receta.all():
			salida += "%d %s de %s, " % (cant.cantidad,cant.ingrediente.stock.medida,cant.ingrediente.nombre)
		return salida[:-2]
	
	def __str__(self):
		return self.nombre

class Pedido(models.Model):
	fecha_pedido = models.DateField(default=date.today)
	fecha_entrega = models.DateField()
	cover = models.CharField(
			max_length=2,
			choices=COVER_CHOICE,
			default=COVER_DEFAULT
		)	
	cliente = models.ForeignKey(Cliente,on_delete=models.CASCADE, blank = True)
	personas = models.IntegerField(default=20)
	capas = models.ForeignKey("CapaPastel",null=True,default=None,on_delete=models.CASCADE)
	base = models.ForeignKey(BasePastel,null=True,default=None,on_delete=models.CASCADE)
	vegano = models.BooleanField(default=False)
	celiaco = models.BooleanField(default=False)

class CapaPastel(models.Model):
	crema = models.CharField(max_length=2,choices=CREMA_CHOICES,default=CREMA_DEFAULT)
	ingredientes = models.ManyToManyField(Material,blank=True)
	
	def get_ingredientes(self):
		salida = ""
		for ingrediente in self.ingredientes.all():
			salida += ingrediente.nombre+", "
		return salida[:-2]
class PerfilUsuario(models.Model):

	user = models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)
	role = models.CharField(max_length=2,choices=TIPO_USUARIO_CHOICES,default=TIPO_USUARIO_DEFAULT)
	rut = models.IntegerField()
	dv = models.CharField(max_length=1,default="")
	fecha_creacion = models.DateTimeField(default=timezone.now)

def regions_changed(sender, **kwargs):
    if kwargs['instance'].ingredientes.count() > 3:
        raise ValidationError("You can't assign more than three regions")


m2m_changed.connect(regions_changed, sender=CapaPastel.ingredientes.through)

core/forms.py
from django import forms
from .models import Stock, Material, Cliente, Pastel, CantReceta, BasePastel, Pedido, CapaPastel, PerfilUsuario


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['cantidad']


class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['tipo', 'nombre', 'stock']


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'apellido', 'mail']


class PastelForm(forms.ModelForm):
    class Meta:
        model = Pastel
        fields = ['nombre', 'vegano', 'celiaco', 'capas', 'base']


class CantRecetaForm(forms.ModelForm):
    class Meta:
        model = CantReceta
        fields = ['ingrediente','cantidad']


class BasePastelForm(forms.ModelForm):
    class Meta:
        model = BasePastel
        fields = ['nombre', 'receta']


class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['fecha_pedido', 'fecha_entrega', 'personas', 'vegano', 'celiaco', 'cliente', 'capas', 'base']


class CapaPastelForm(forms.ModelForm):
    class Meta:
        model = CapaPastel
        fields = ['crema', 'ingredientes']


class PerfilUsuarioForm(forms.ModelForm):
    class Meta:
        model = PerfilUsuario
        fields = ['role', 'rut', 'dv',]

core/views.py
from django.shortcuts import render
from core.models import *
from django.http import JsonResponse
from django.utils.datastructures import MultiValueDictKeyError
from .forms import MaterialForm
# Create your views here.

def index(request):
	data = {}
	data['inicio'] = 'Bienvenidos'
	template_name = 'index.html'
	return render(request,template_name,data)

def ingresar_stock(request):
	data = {}
	if request.method == "POST":
		mater = request.POST["material"]
		cantidad = request.POST["cantidad"]
		mater = Material.objects.get(pk=int(mater))
		print (mater.nombre)
		mater.stock.cantidad += int(cantidad)
		print (mater.stock.cantidad)
		mater.stock.save()
		mater.save()
		select = "#cant_"+str(mater.pk)
		cant = mater.total()
		data = {
			"cant":cant,
			'select':select}
		print ("DATA ", data)
		
		return JsonResponse(data)
	else:
		material = Material.objects.all()
		stock = Stock.objects.all()
		data["materiales"] = material
	
	data["titulo"] = "Agregar Stock"
	data["tabla"] = "Tabla de Materiales"
	template_name = 'ingresar_stock.html'
	return render(request, template_name, data)

def crearMaterial(request):
	data = {}
	if request.method == "POST":
		medida = request.POST["medida"]
		tipo = request.POST["tipo"]
		nombre = request.POST["nombre"]
		cantidad = request.POST["cantidad"]
		stock = Stock.objects.create(
			medida = medida,
			cantidad = cantidad,
			)
		stock.save()
		mater = Material.objects.create(
			tipo = tipo,
			nombre = nombre,
			stock= stock,
			)
		mater.save()
		html = "<tr>\
					<td>%s</td>\
					<td>%s</td>\
					<td>%s</td>\
					<td>%s</td>\
		</tr>" %(nombre,mater.pk,tipo,stock)
		data = {
			"html":html,
		}
	return JsonResponse(data)

def admin_usuario(request):
	data = {}
	if request.method == "POST":
		n_user = User.objects.create_user(
			username=request.POST["rut"],
			password=request.POST["name"].split(" ")[0]+request.POST["dv"],
			email=request.POST['email'],
			first_name=request.POST["name"],
			last_name=request.POST['last_name'],
		)
		n_user.save()
		
		n_perfil = PerfilUsuario.objects.create(
			user = n_user,
			role = request.POST["tipo"],
			rut = request.POST['rut'],
			dv = request.POST['dv']
		)
		n_perfil.save()
		
		if request.POST['tipo'] == "CO":
			if Cliente.objects.filter(mail=request.POST['email']).exists():
				cliente = Cliente.objects.get(email=request.POST['email'])
				cliente.userprofile = n_perfil
				cliente.save()
			else:
				n_cliente = Cliente.objects.create(
					nombre = n_user.first_name,
					apellido = n_user.last_name,
					mail = n_user.email
				)
				n_cliente.save()
		elif request.POST['tipo'] == 'AD':
			n_user.is_staff = True
			n_user.save()
		return JsonResponse({'mensaje':'El usuario ha sido creado con éxito. \n La contraseña es una combinación de su primer y su dígito verificador.'})
	else:
		data['users'] = PerfilUsuario.objects.all()
		template_name = 'perfil_usuario/admin_usuarios.html'
		return render(request,template_name,data)
	
def admin_pastel(request):
	data = {}
	if request.method == "POST":
		return JsonResponse({'mensaje':'El usuario ha sido creado con éxito. \n La contraseña es una combinación de su primer y su dígito verificador.'})
	else:
		data['pasteles'] = Pastel.objects.all()
		data['bases'] = BasePastel.objects.all()
		data['ingredientes'] = Material.objects.filter(tipo="IT").all()
		data['materiales'] = Material.objects.filter(tipo="MP").all()
		template_name = 'pastel/admin_pastel.html'
		return render(request,template_name,data)

def pedidos(request):
	data = {}
	data['pasteles'] = Pastel.objects.all()
	data['bases'] = BasePastel.objects.all()
	data['ingredientes'] = Material.objects.filter(tipo="IT").exclude(stock__cantidad=0).all()
	data['materiales'] = Material.objects.filter(tipo="MP").exclude(stock__cantidad=0).all()
	
	template_name = 'pedi_clie.html'
	return render(request,template_name,data)

def create_base(request):
	name = request.POST['nombre_input']
	n_base = BasePastel.objects.create(
		nombre = name
	)
	n_base.save()
	i = 0
	while i < 200:
		try:
			ing_pk = request.POST['ing_'+str(i)]
			print("Esta es la ing_pk ",ing_pk)
			ingrediente = Material.objects.get(pk=ing_pk)
			cantidad = request.POST['cant_'+str(i)]
			receta = CantReceta.objects.create(
				ingrediente = ingrediente,
				cantidad = cantidad
			)
			receta.save()
			n_base.receta.add(receta)
			i+=1
		except MultiValueDictKeyError:
			break
	return JsonResponse({"mensaje":"ok"})

def create_pastel(request):
	name = request.POST['pastel_input']
	cover = request.POST['cover_input']
	base = request.POST['base_input']
	image = request.POST['img_pastel']
	pastel = Pastel.objects.create(
		nombre = name,
		cover = cover,
		base = base,
		image = image,
	)
	pastel.save()

	i = 0
	while i < 200:
		try:
			crema = request.POST['cre_'+str(i)]
			capa = CapaPastel.objects.create(
				crema = crema,
			)
			capa.save()
			try:
				ing_pk = request.POST.getlist('ing_'+str(i)+'[]')
				for pk in ing_pk:
					ingrediente = Material.objects.get(pk=pk)
					capa.ingredientes.add(ingrediente)
					capa.save()
			except:
				ingrediente = Material.objects.get(pk=ing_pk)
				capa.ingredientes.add(ingrediente)
				capa.save()
				ing_pk = request.POST['ing_'+str(i)]
				
			i+=1
		except MultiValueDictKeyError:
			break

	return JsonResponse({"mensaje":"ok"})

core/templates/create_bake.html
{% extends "base.html" %} {% load bootstrap4 %} {% load static %} 
{% block css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock css%}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col">
			
		</div>
	</div>
</div>
{% endblock content %}

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script>
	$(document).ready(function () {
		$(".select2").select2();
		$("#tc_list").addClass("active");
		
		$('.datepicker').datepicker({ format: 'dd/mm/yyyy' });
		
	});
</script> 
{% endblock javascript %}

core/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container" >
	<div class="row">
		<div class="col-12">
			<div class="card text-center">
				<div class="card-header bg-title text-white">
				  <strong class="card-name">Haz tu pedido!</strong> 
				</div>
				<div class="card-body">
				  <h5 class="card-title">Personaliza tu pastel</h5>
				  <p class="card-text">O tambien puedes elegir entre todas nuestras variedades!</p>
				  <a href="{% url 'pedidos' %}" class="btn btn-primary">Realizar Pedido</a>
				</div>
				<div class="card-footer bg-footer text-muted">
				  <p class="footer">
					  Tambien puedes <a class="footer-a" href="#">registrarte</a> para agilizar tus próximas compras... 
				  </p> 
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}
{% block javascript %}
{% endblock javascript %}

core/templates/ingresar_stock.html
{% extends "base.html" %} {% load bootstrap4 %} {% load static %} 
{% block css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock css%}

{% block content %}
<div class = "container">
	<div class="row">
		<div class="col-lg-12 col-offset-4">
			<div class="card">
				<h5 class="card-header">{{tabla}}</h5>
				<div class="card-body">
					<div class="row">
						<div class="col">
					<h5 class="card-title">Stock de Materiales en sistema.</h5>
						</div>
						<div class="col">
					<button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#ModalStock">Ingresar Stock</button>
						</div>
			  			<div class="col">
			  			<!-- Button trigger modal -->
						<button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#AgregarMaterial">Agregar Material</button>
			  			</div>
					</div>
					<!-- Button trigger modal -->
					<p class="card-text"></p>
					<table class="table table-bordered" id="tabla1">
					    <thead>
					        <tr>
					            <th scope="col">Nombre</th>
					            <th scope="col">Codigo</th>
					            <th scope="col">Tipo</th>
					            <th scope="col">Stock</th>
					        </tr>
					    </thead>
					    <tbody id="tbody">
					        {% for material in materiales %}
					        <tr>
					            <td>{{ material.nombre }}</td>
					            <td>{{ material.pk }}</td>
					            <td>{{ material.tipo }}</td>
					            <td id="cant_{{material.pk}}">{{ material.total }}</td>
					        </tr>
					        {% endfor %}
					    </tbody>
					</table>
				</div>
			</div>
		</div>
	</div>	
</div>
<div class="container">
	<div class="row">
		<div class="col">
			<!-- Modal -->
			<div class="modal fade" id="ModalStock" tabindex="-1" role="dialog" aria-labelledby="ModalStockLabel" aria-hidden="true">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h5 class="modal-title" id="ModalStockLabel">{{titulo}}</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
			      	<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
						<div class="form-group row">
						<label class="col-md-3 col-form-label" for="id_material">Material</label>
						<div class="col-md-9">
							<select name="material" class="form-control" id="id_material" title="" required="">
							{% for material in materiales %}
							<option value="{{material.pk}}">{{material.nombre}} ({{material.total}})</option>
							{% endfor %}
							</select>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-md-3 col-form-label" for="id_cantidad">Cantidad:</label>
						<div class="col-md-9">
	  						<input type="number" class="form-control" name="cantidad" id="id_cantidad" required="">
	  					</div>
					</div>
					</form>
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<a type="submit" value="Enviar" id="enviar" class="btn btn-primary text-white"  data-dismiss="modal">Enviar</a>
			      </div>
			    </div>
			  </div>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col">
			

			<!-- Modal -->
			<div class="modal fade" id="AgregarMaterial" tabindex="-1" role="dialog" aria-labelledby="AgregarMaterialLabel" aria-hidden="true">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h5 class="modal-title" id="AgregarMaterialLabel">Agregar Material</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
						<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
							<div class="form-group row">
								<label class="col-md-3 col-form-label" for="id_nombre">Nombre:</label>
								<div class="col-md-9">
			  						<input type="text" class="form-control" name="nombre" id="id_nombre" required="">
			  					</div>
							</div>
							<div class="form-group row">
								<label class="col-md-3 col-form-label" for="id_tipo">Tipo:</label>
								<div class="col-md-9">
									<select name="material" class="form-control" id="id_tipo" title="" required="">
									<option value="MP">Materia Prima</option>
									<option value="IT">Ingredientes de Torta</option>
									</select>
								</div>
							</div>
							<div class="form-group row">
								<label class="col-md-3 col-form-label" for="id_medida">Medida:</label>
								<div class="col-md-9">
									<select name="material" class="form-control" id="id_medida" title="" required="">
									<option value="GR">Gramos</option>
									<option value="CC">Centimetros Cubicos</option>
									<option value="UN">Unidad</option>
									</select>
								</div>
							</div>
							<div class="form-group row">
								<label class="col-md-3 col-form-label" for="id_cantidadA">Cantidad:</label>
								<div class="col-md-9">
			  						<input type="number" class="form-control" name="cantidadA" id="id_cantidadA" required="">
			  					</div>
			  				</div>
						</form>
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<a type="submit" value="Enviar" id="enviar2" class="btn btn-primary text-white"  data-dismiss="modal">Enviar</a>
			      </div>
			    </div>
			  </div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script>
	$(document).ready(function () {
		$(".select2").select2();
		$("#tc_list").addClass("active");
		
		$('.datepicker').datepicker({ format: 'dd/mm/yyyy' });
		
	});
</script>
<script>
	  $(document).ready(function(){
        $("#enviar").click(function(){
            var material = $('#id_material').val();
            var cantidad = $('#id_cantidad').val();
            var data = {
                csrfmiddlewaretoken: "{{csrf_token}}",
                material: material,
                cantidad: cantidad,
            }

            $.ajax({
                type: "POST",
                url: "{% url 'add_stock' %}",
                data: data,
                success: function(response){
                    swal("Exito!","Todo bien por aca.","success");
                    $("#enviar").html(response.mensaje);
                    $(response.select).html(response.cant);
                },
                error: function(){
                    swal("Error!","Salio todo mal.","warning");
                },

            });
        });
     	$("#enviar2").click(function(){
            var nombre = $('#id_nombre').val();
            var tipo = $('#id_tipo').val();
            var medida = $('#id_medida').val();
            var cantidad = $('#id_cantidadA').val();
            var data = {
                csrfmiddlewaretoken: "{{csrf_token}}",
                nombre: nombre,
                tipo: tipo,
                medida: medida,
                cantidad: cantidad,
            }

            $.ajax({
                type: "POST",
                url: "{% url 'add_material' %}",
                data: data,
                success: function(response){
                    swal("Exito!","Todo bien por aca.","success");
                    $("#tbody").append(response.html);
                },
                error: function(){
                    swal("Error!","Salio todo mal.","warning");
                },
            });
                console.log(data)

        });
    });
</script>
{% endblock javascript %}